AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  AWS SAM project to deploy an IAM role creation service API

Metadata:
  'AWS::ServerlessRepo::Application':
    Name: role-creation-service
    Description: >
      AWS SAM project to deploy an IAM role creation service API
      Includes: API Gateway, Lambda
    Author: smoketurner
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['organization', 'org', 'apigateway', 'apigw', 'lambda', 'iam', 'account', 'sqs']
    HomePageUrl: https://github.com/smoketurner/sam-iam-role
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/smoketurner/sam-iam-role

Parameters:
  ExecutionRoleName:
    Type: String
    Default: RoleCreationExecution
    Description: Name of the IAM role in the target account

Globals:
  Function:
    Runtime: python3.8
    CodeUri: src/handlers/
    MemorySize: 1024 # megabytes
    Timeout: 5 # seconds
    Environment:
      Variables:
        EXECUTION_ROLE_NAME: !Ref ExecutionRoleName
        RCS_LOG_LEVEL: DEBUG

Resources:
  RoleCreationAdmin:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: RoleCreationAdmin
      Description: !Sub 'DO NOT DELETE - Used by Role Creation Service. Created by CloudFormation ${AWS::StackId}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: RoleCreationAdminPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sts:AssumeRole'
                Resource: !Sub 'arn:${AWS::Partition}:iam::*:role/${ExecutionRoleName}'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'

  CreateRolesLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: create_roles.lambda_handler
      Description: Create new IAM roles Lambda handler
      Role: !GetAtt RoleCreationAdmin.Arn

  EvaluatePolicyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: evaluate_policy.lambda_handler
      Description: Evaluate IAM policy Lambda handler
      Role: !GetAtt RoleCreationAdmin.Arn

  VerifyRolesLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: verify_roles.lambda_handler
      Description: Verify IAM roles Lambda handler
      Role: !GetAtt RoleCreationAdmin.Arn

  StatesExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              Service: !Sub states.${AWS::Region}.amazonaws.com
            Effect: Allow
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource: '*'
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt 'CreateRoleLambdaFunction.Arn'
                  - !GetAtt 'EvaluatePolicyLambdaFunction.Arn'
                  - !GetAtt 'VerifyRoleLambdaFunction.Arn'
                Condition:
                  ArnLike:
                    'aws:SourceArn': !Sub 'arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*'

  StateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      DefinitionString: !Sub |-
        {
          "Comment": "Role Creation Process",
          "StartAt": "IsValidRequestType",
          "States": {
            "IsValidRequestType": {
              "Type": "Choice",
              "Choices": [
                {
                  "Or": [
                    {
                      "Variable": "$.type",
                      "StringEquals": "iam"
                    },
                    {
                      "Variable": "$.type",
                      "StringEquals": "sns_topic"
                    },
                    {
                      "Variable": "$.type",
                      "StringEquals": "s3_bucket"
                    },
                    {
                      "Variable": "$.type",
                      "StringEquals": "vpce"
                    }
                  ],
                  "Next": "EvaluatePolicy"
                }
              ],
              "Default": "InvalidType"
            },
            "EvaluatePolicy": {
              "Type": "Task",
              "Resource": "${EvaluatePolicyLambdaFunction.Arn}",
              "TimeoutSeconds": 60,
              "Next": "IsCompliant"
            },
            "InvalidType": {
              "Type": "Fail"
            },
            "IsCompliant": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.result",
                  "StringEquals": "COMPLIANT",
                  "Next": "CreateRoles"
                },
                {
                  "Variable": "$.result",
                  "StringEquals": "UNSUPPORTED",
                  "Next": "UnsupportedType"
                }
              ],
              "Default": "NonCompliant"
            },
            "CreateRoles": {
              "Type": "Task",
              "Resource": "${CreateRolesLambdaFunction.Arn}",
              "Next": "VerifyRoles",
              "TimeoutSeconds": 60
            },
            "VerifyRoles": {
              "Type": "Task",
              "Resource": "${VerifyRolesLambdaFunction.Arn}",
              "Retry": [
                {
                  "ErrorEquals": ["RetryError"],
                  "IntervalSeconds": 10,
                  "BackoffRate": 1.0,
                  "MaxAttempts": 500
                }
              ],
              "TimeoutSeconds": 60,
              "Next": "RolesCreated"
            },
            "NonCompliant": {
              "Type": "Fail"
            },
            "UnsupportedType": {
              "Type": "Fail"
            },
            "RolesCreated": {
              "Type": "Succeed"
            }
          }
        }
      RoleArn: !GetAtt StatesExecutionRole.Arn
